# Generated by Django 4.1.3 on 2022-11-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Digimons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('href', models.URLField()),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialMove', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeD', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XrosWars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Ultimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Rookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Mega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Hybrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('profile', models.TextField(max_length=300, verbose_name='Description')),
                ('xAntibody', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Attribute')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level', verbose_name='Level')),
                ('specialMove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specialmove', verbose_name='SpecialMove')),
                ('typeD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typed', verbose_name='Type')),
            ],
        ),
    ]
