# Generated by Django 4.1.3 on 2022-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_armor_specialmove_remove_champion_specialmove_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='digimons',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='mega',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mega',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='rookie',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rookie',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='trainingi',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trainingi',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='trainingii',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trainingii',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
        migrations.AlterField(
            model_name='xroswars',
            name='profile',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='xroswars',
            name='specialMove',
            field=models.ManyToManyField(blank=True, to='api.specialmove', verbose_name='SpecialMove'),
        ),
    ]
